<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>This package adds a ScopeSetId column to CK.tUserTwitter table.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.Auth.AuthScope" Version="29.0.1--ci.1" />
    <ProjectReference Include="..\CK.DB.User.UserTwitter\CK.DB.User.UserTwitter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" />
  </ItemGroup>
</Project>